### ISSUE TITLE
小伙子精力过剩，佩服佩服

### ISSUE THREAD

**Issue by joostshao** [Cirru/stack-editor#1]
小伙子精力过剩，佩服佩服

**Comment by tiye** [comment]
Please submit issue with an English title, however Chinese description is fine.

倒不是精力过剩, 这个东西太重要了, 我不得不花大量的精力去想怎么实现. 而且编程经常是一件极其无聊的工作, 如果不找点有意思的做给自己打鸡血, 恐怕会坚持不下去.

有兴趣的话安装一个试用一下. 关了.
